# Generated by Django 3.2 on 2021-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtranscribe', '0002_alter_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
